# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

envd = HYPRCURSOR_SIZE,24
envd = XCURSOR_SIZE,24
envd = QT_CURSOR_SIZE,24
envd = XDG_CURRENT_DESKTOP,Hyprland
envd = XDG_SESSION_DESKTOP,Hyprland
# envd = GTK_IM_MODULE,fcitx5
envd = QT_IM_MODULE,fcitx5
envd = XMODIFIERS,@im=fcitx5
envd = INPUT_METHOD,fcitx5
envd = LIBVA_DRIVER_NAME,nvidia
envd = __GLX_VENDOR_LIBRARY_NAME,nvidia